name = "FdgPet"
uuid = "6c748940-0faa-4da0-9c80-a2e38384b490"
authors = ["tm-schwartz <tm.sc@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
